### ISSUE TITLE
[Question] How to decrypt after encryption?

### ISSUE THREAD

**Issue by pbalan** [mekuanent/loopback-encryption-mixin#1]
Hi,

Thanks for working on this.

I was wondering on how to decrypt the text from database after encryption? Could you please post a sample?

Thanks.

**Comment by pbalan** [comment]
Guess the answer I was looking for was in the package.json
**"description": "A mixin that transparently encrypts fields of a module at a save and decrypts fiels at get.",**

**Comment by mekuanent** [comment]
@pbalan the mixin automatically does it for you whenever you do find/load operations.
