### ISSUE TITLE
Need to decrypt value from row query using datasource

### ISSUE THREAD

**Issue by gtl-hardik** [mekuanent/loopback-encryption-mixin#2]
I am using loopback framework along with this plugin to encrypt data in a table.

I am having some node script where I need to run a static query using the Datasource connection query.

In this situation, I need to decrypt the already encrypted saved value from the database. I am having salt and all other values there but don't know how can I decrypt it.

We should have some functionality for row queries as well. Or let me know how can I do decryption of the database fetched values. 

Thanks

**Comment by mekuanent** [comment]
you can easily do it by using crypto lib

`crypto.pbkdf2(your_password, your_salt, your_iteration, your_hashBytes, your_hashAlgorithm, `
 `                      (err, derivedKey) => {`
 `                           let cipher = crypto.createDecipheriv(your_encryptionAlgorithm, derivedKey, iv);`
 `                           let decrypted = cipher.update(your_text, 'hex', 'utf8');`
 `                           decrypted += cipher.final('utf8');`
 `   });`
